In [ ]:
import glob
import numpy as np
files=glob.glob('data/*/*/*.txt')

In [ ]:
files[0]

In [ ]:
loc='data\\Day1\\Anand_5min\\NFB_17-5-2019_14-44.txt'
loc=files[0]
a=np.genfromtxt(files[0], delimiter=',')

In [ ]:
arr=[]
arr.append(a)

In [ ]:
arr

In [ ]:
from numpy import array
from keras.models import Sequential

In [ ]:
import tensorflow as tf

# do not delete

In [ ]:
import pandas as pd
import os
import numpy as np
import glob

In [ ]:
loc='data\\Day1\\Anand_5min\\NFB_17-5-2019_14-44.txt'
arr=np.genfromtxt(loc, delimiter=',')
arr=arr[:-1]

In [ ]:
arr=np.reshape(arr,(-1,35))

In [ ]:
arr_new=[]
for i in range(arr.shape[0]-1):
    if np.equal(np.array(arr[i]),np.array(arr[i+1])).all() == False:
        print(i)
        arr_new.append(arr[i])

In [ ]:
print(arr[721])
print(arr[735])

In [ ]:
arr_new=np.array(arr_new)
arr_new.shape
arr1=arr_new[0:100]

In [ ]:
Z=arr1
from matplotlib import cm
my_col = cm.jet(np.random.rand(Z.shape[0],Z.shape[1]))
#my_col = cm.jet(np.random.rand(Z.shape[0]))
#print(np.(my_col[99]))
import numpy as np
from mpl_toolkits.mplot3d import Axes3D  
# Axes3D import has side effects, it enables using projection='3d' in add_subplot
import matplotlib.pyplot as plt
%matplotlib widget
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
x=np.arange(0,35)
y = np.arange(0,100)
X, Y = np.meshgrid(x, y)
ax.plot_surface(X, Y, Z,facecolors = my_col)

In [1]:
import numpy as np
from keras.layers import Input, Dense
from keras.models import Model
from keras.datasets import mnist
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [2]:
encoding_dim = 32 # 32 floats -> compression of factor 24.5, assuming the input is 784 floats
 
# this is our input placeholder
input_img = Input(shape=(784,))
# "encoded" is the encoded representation of the input
encoded = Dense(encoding_dim, activation='relu')(input_img)
# "decoded" is the lossy reconstruction of the input
decoded = Dense(784, activation='sigmoid')(encoded)
# this model maps an input to its reconstruction
autoencoder = Model(input_img, decoded)
# this model maps an input to its encoded representation
encoder = Model(input_img, encoded)
# create a placeholder for an encoded (32-dimensional) input
encoded_input = Input(shape=(encoding_dim,))
# retrieve the last layer of the autoencoder model
decoder_layer = autoencoder.layers[-1]
# create the decoder model
decoder = Model(encoded_input, decoder_layer(encoded_input))
# configure our model to use a per-pixel binary crossentropy loss, and the Adadelta optimizer:
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
(x_train, _), (x_test, _) = mnist.load_data()
# normalize all values between 0 and 1 and we will flatten the 28x28 images into vectors of size 784.
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = x_train.reshape((len(x_train), np.prod(x_train.shape[1:])))
x_test = x_test.reshape((len(x_test), np.prod(x_test.shape[1:])))
print (x_train.shape)
print (x_test.shape)

(60000, 784)
(10000, 784)


In [1]:
import numpy as np

In [9]:
a=[[1,2,3],[23,45,6]]
a=np.array(a)
a.T-np.mean(a,axis=1)


array([[ -1.        ,  -1.66666667],
       [  0.        ,  20.33333333],
       [  1.        , -18.66666667]])

In [20]:
a=np.genfromtxt('data_for_clustering.csv', delimiter=',')
a=a[:-1]
print(a[1])
x=a[:250*910]
x=x[20*250:]
x=x.reshape(-1,250)
me=np.mean(x,axis=1)
x=(x.T-me).T

39963.59


In [ ]:
#single layer
encoding_dim = 10
 
# this is our input placeholder
input_img = Input(shape=(250,))
# "encoded" is the encoded representation of the input
encoded = Dense(encoding_dim, activation='linear')(input_img)
# "decoded" is the lossy reconstruction of the input
decoded = Dense(250, activation='linear')(encoded)
# this model maps an input to its reconstruction
autoencoder = Model(input_img, decoded)
# this model maps an input to its encoded representation
encoder = Model(input_img, encoded)
# create a placeholder for an encoded (10-dimensional) input
encoded_input = Input(shape=(encoding_dim,))
# retrieve the last layer of the autoencoder model
decoder_layer = autoencoder.layers[-1]
# create the decoder model
decoder = Model(encoded_input, decoder_layer(encoded_input))
autoencoder.compile(optimizer='adam', loss='mse')#binary_crossentropy

In [ ]:
#3layer
encoding_dim = 10
 
# this is our input placeholder
input_img = Input(shape=(250,))
# "encoded" is the encoded representation of the input
encoded0=Dense(100,activation='linear')(input_img)
encoded = Dense(encoding_dim, activation='linear')(encoded0)
# "decoded" is the lossy reconstruction of the input
decoded0=Dense(100,activation='linear')(encoded)
decoded = Dense(250, activation='linear')(decoded0)
# this model maps an input to its reconstruction
autoencoder = Model(input_img, decoded)
# this model maps an input to its encoded representation
encoder = Model(input_img, encoded)
# create a placeholder for an encoded (10-dimensional) input
encoded_input = Input(shape=(10,))
# retrieve the last layer of the autoencoder model
decoder_layer = autoencoder.layers[-2]
# create the decoder model
decoder = Model(encoded_input, decoder_layer(encoded_input))
autoencoder.compile(optimizer='adam', loss='mse')#binary_crossentropy

In [ ]:
autoencoder.fit(x,x,
epochs=50,
batch_size=10)

In [ ]:
encoded_layer1=encoder.predict(x)
decoded_output1=decoder.predict(encoded_layer1)
decoder_layer1 = autoencoder.layers[-1]
encoded_input1 = Input(shape=(100,))
# create the decoder model
decoder1 = Model(encoded_input1, decoder_layer1(encoded_input1))
decoded_output2=decoder1.predict(decoded_output1)


In [28]:
#CNN
model=Sequential()
pool_size=10
model.add(Conv1D(8,10, input_shape=x.shape[1:],activation='linear',padding='same'))
model.add(AveragePooling1D(pool_size=(5),padding='same'))

model.add(Conv1D(2,10,padding='same',activation='linear'))
model.add(AveragePooling1D(pool_size=(5),padding='same'))

#model.add(Conv1D(1,5,padding='same',activation='linear'))
#model.add(AveragePooling1D(pool_size=(5),padding='same'))

#model.add(Conv1D(1,5,padding='same',activation='linear'))
#model.add(UpSampling1D(5))

model.add(Conv1D(2,10,padding='same',activation='linear'))
model.add(UpSampling1D(5))

model.add(Conv1D(8,10,padding='same',activation='linear'))
model.add(UpSampling1D(5))

model.add(Conv1D(1,10, padding='same'))


model.compile(loss='mse',
              optimizer='adam',
              metrics=['accuracy'])

array([[[1],
        [2],
        [3]],

       [[3],
        [4],
        [5]]])

In [5]:
import numpy as np
a=np.array([[1,2,3,4],[1,2,3,4]])
b=np.array([3,4,5,6])
a*b

array([[ 3,  8, 15, 24],
       [ 3,  8, 15, 24]])

In [7]:
pow(np.array([2,3,4]),2)

array([ 4,  9, 16], dtype=int32)

In [11]:
a=np.array([[1,2,3,4,5,7],[4,5,6,7,8,9]])
np.sum(a.reshape(2,2,3),axis=2)

array([[ 6, 16],
       [15, 24]])

In [13]:
a=np.array([[1,2,3],[3,4,5]])
a/np.array([1,2,3])

array([[1.        , 1.        , 1.        ],
       [3.        , 2.        , 1.66666667]])

# downloading a model and changing it

In [5]:
import keras
vgg19=keras.applications.vgg19.VGG19()
vgg19.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________